services:
  - type: web
    name: employee-management-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn employee_management.wsgi
    autoDeploy: true
