# Generated by Django 5.1.2 on 2024-10-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(blank=True, choices=[('HR', 'hr'), ('ENGINEER', 'engineer'), ('SALES', 'sales')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('MANAGER', 'manager'), ('DEVELOPER', 'developer'), ('ANALYST', 'analyst')], max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
